import React from 'react';

import Layout from '../components/Layout';
import SEO from "../components/Seo"
import pic from '../assets/images/03.jpg';

const IndexPage = () => (
  <Layout>
  <SEO title="Beside the Waves" description="With only a message in a bottle to give them hope, two girls battle a world in ruin." />
    <div id="main">
    <div className="inner">
    <header>
    <div className="resumeTitle">
  <h1>Beside the Waves</h1><h4>6,034 words | Post-Apocalyptic</h4>
  </div>
    </header>
      <section>
        <div className="box alt">
						<div className="row gtr-uniform">
							<div className="col-12"><span className="image fit"><img src={pic} alt="" /></span></div>
						</div>
          </div>
        <div className="storyText">
       <p>A row of rusted oil barrels and tires led to a pathway carved by weary footsteps. Whether it was the constant screams in the night or the roaring flames sparked by clan wars, rarely did one have a moment to sit and enjoy peace. Even the thought of peace was all but a distant memory.</p>
       <p>As our bare feet pressed into the sand, we dodged shards of glass and metal. The beaches had become both sprawling junkyards and the last hope we had of finding treasure. Had it been solely my own choice, I would have called off the search years ago once the Dieselheads made the south side their home. But there was nothing on this Earth that was going to stop Rowan from combing the shorelines.</p>
       <p>“Check the net under the bridge,” she called to me, “The rains were pushing the waters past there. Something’s got to have been caught up in it.”</p>
       <p>Sixteen nets staggered across every nook and cranny on the beach— I had to admire her work ethic. If that bottle was anywhere in the entire ocean, I expected her to be the one to find it. But if I were to tell the truth, I didn’t believe that such a thing actually existed.</p>
       <p>You’d think we’d be up to our eyeballs in fish from the number of nets we left to rest in the water, but like most things, the ocean was barren of life. If it wasn’t holed up in the shelters by the time the bombs went off, it was safe to say that it had boiled from the inside out.</p>
       <p>Rowan may have had the energy to do more than sleep, breathe, and eat, but I was growing weary both in body and in mind. Our supplies were limited, and the lands that we once called home had become a battleground for the Dieselheads to bash each other’s skulls.</p>
       <p>Still, I didn't have the heart to force my sister away from that place. I may have become jaded, but there was still light in her eyes. And that… that I refused to take away from her.</p>
       <p>“Gwen! Gwen, look! I found something!” she screamed from across the beach.</p>
       <p>I ran to her, wincing as sharp rocks and old cans dug into the soles of my feet. She was kneeling by the water’s edge. From where I stood, I couldn’t make out what she was holding, but my heart pounded. <i>“No way,”</i> I thought to myself, <i>There’s no way she actually found it.”</i>“ </p>
       <p>Sitting beside my sister, I brushed her tattered brown curls out of her face and watched her closed palms, “What is it? What did you find?”</p>
       <p>She looked at me with a wide grin before revealing the object in her hands— a broken clamshell in a soft opal shade. I sighed. Such things may have been easy enough to entertain her, but we were in danger just setting foot on that soil. Often I attempted to feign my interest for Rowan’s sake, but at that moment, I could no longer will myself to smile.</p>
       <p>“You don’t like it? Is it because it’s broken? This is the biggest shell piece I’ve found yet! You know, if we get enough of them we can grind them into a powder and-”</p>
       <p>My eyes grew wide. I heard it in the distance— the motors were roaring along the cliffside road. I wasn’t able to spot them from where I sat, but that didn’t mean they couldn’t spot us. </p>
       <p>“Come on!” I screamed as I pulled Rowan’s arm.</p>
       <p>“No! Wait! Not yet! I still have to check the rest of the nets!”</p>
       <p>Rowan thrashed and clawed at me as I scooped her into my arms. Just days shy of her tenth birthday, it wouldn’t be long until she was too big for me to carry away. And when that day came, I knew my job of keeping her safe was only going to get increasingly difficult.</p>
       <p>She bit into my hand, and I squealed. Ornery as usual, Rowan had no desire to do anything outside of her own plans. And I suppose part of me understood some of those sentiments… at least to a degree. She believed what she was searching for was the answer that would save us from this monotony. How could I tell her that nothing could ever go back to being ‘normal’?</p>
       <p>The sun blinded my eyes as I tried to run after my sister. She ran along the beach, sending waves and sand splashing into the air. Her focus was on that final net, but I couldn’t keep my eyes off of the cliffs. The roaring sound of motors was drawing near. And as the scent of diesel wafted into my nostrils, I feared we hadn’t much time left until we needed to be hidden out of sight.</p>
       <p>Stumbling over a piece of birch driftwood, Rowan crawled into the sand and reached for the net. A glimmer caught her eyes, and she gasped. As much as I loved seeing a smile spread across her face, the only emotion I could fathom was fear; tires made their way onto the beach. </p>
       <p>Covering her mouth, I grabbed Rowan and pulled her back towards the hoards of scrap metal. We didn’t have time to flee back to our makeshift shack of a home. But if I could get us nestled away in a tower of tires or an overturned truck then we’d have a chance of remaining unseen. </p>
       <p>My eyes locked onto her own. I whispered to her, “You have to stay quiet. When they leave, we can check the nets again. But first-”</p>
       <p>Rowan pulled my hand away from her mouth. She may not have enjoyed my plan, but she seemed to at least understand. She remained silent as she barreled ahead and hopped into the front seat of a bashed up truck. It was guarded by a row of scrapped fencing and what I could only assume had once been a street lamp. Safety was never something we could take for granted, but I didn’t expect the Dieselheads to come looking in such a remote part of the beach.</p>
       <p>It wasn’t spare parts nor metal scraps that they sought most. After all, they claimed every junkyard, gas station, and dealership in the city as their main bases of operations. What they were after was organic. And given that anyone smart enough to know better had already fled the city, humans were a rare commodity.</p>
       <p>Black smoke rose, and I pulled Rowan flush against the seat. She wanted to see what was going on despite the danger. At most, we could peek from the bottom of the truck window. And even then, we were only putting ourselves at risk. One of the engines halted. It seemed like the dieselheads wanted to take a closer look.</p>
       <p>From behind a tower of tires, I spotted him— a boy not much older than myself with hair caked in mud and oil. And behind him were a crowd of adults who kicked and combed through the trash and scraps. Whatever they were looking for, it was enough that they had brought an entire team.</p>
       <p>My heart pounded. I knew they had to have known we were in the city. It was only a matter of time. We hadn’t done the best job at being stealthy as we waded through the beach, leaving evidence of our existence in our wake. And if they were able to locate us here, I had to worry that our home wasn’t safe either.</p>
       <p>The boy’s eyes darted towards the water. It wasn’t the chilling waves or warm, beating sun that attracted his attention— it was the glimmer from the net. Rowan noticed it just as I did because she lunged forward. I restrained and held her mouth once more. Whatever sparkled in the net, it wasn’t worth our lives. </p>
       <p>“Take a look at this!” he screamed.</p>
       <p>In mind, I hoped it was only a seashell. If it were something insignificant then I could promise Rowan another. I would become her personal seashell-picking slave for the rest of my life if I had to. But as fate loved to be cruel at times, he had to have found the one thing she would never let go.</p>
       <p>“It’s a bottle! Come check this out!” </p>
       <p>I wrestled with my sister as she attempted to lunge out of the window. In my mind, I knew it couldn’t have been the bottle she was after. There had to be millions of bottles left to rot as trash in the ocean. That the Dieselheads had found the very one that contained the message was the most unlikely scenario I could have imagined. But I suppose I never expected the world to end either.</p>
       <p>Despite her teeth piercing my flesh, I held her tightly against me. Tears were welling in her eyes. It was more than likely that she’d never forgive me. But my focus was on our future. Whether we had the bottle or if it was lost in the hands of some lunatics, none of that mattered if we were both dead.</p>
       <p>Her blood and sand-covered feet pounded into the truck door. She truly wasn’t giving up without a fight. I whispered to her, “Think about this rationally. We don’t even know what they found yet.”</p>
       <p>That, though, did nothing to ease her thrashing. I tried once more, “Listen. Rowan. I’m going to release my hands. Promise me you’re only going to look. If you don’t want both of us to die, you’ll calm down.”</p>
       <p>She was appeased. At least, for that moment. She hopped up against the bottom edge of the driver side window and watched as the mud-caked boy waved the bottle in the air. He seemed pleased with his efforts. His ‘friends’, though, didn’t share the same sentiment. They struck him and pointed towards the towers of junk. The boy collapsed to the ground, and the bottle rolled along the beach.</p>
       <p>Rowan’s eyes grew wide, “Do you see it?”</p>
       <p>“Shh!” I whispered, “What do you expect? The Dieselsheads are a bunch of brutes. What do you expect them to do to us if-”</p>
       <p>“No!” she screamed entirely too loud, “The bottle! Look!”</p>
       <p>My eyes watched the wine-stained glass roll into a ditch in the sand. With the bright-shining sun shooting its rays, I was able to peer inside and see the contents— a letter wrapped away in a plastic bag. My heart sank. As happy as I was that Rowan had found what she was looking for, she had also attracted the attention of the boy.</p>
       <p>He jumped to his feet and darted his head towards the towers of tires, “I hear something! A voice! Someone’s here!”</p>
       <p>Regardless of the fear pumping through my veins, I grabbed a hold of Rowan’s arm and dragged her out of the truck. She struggled and wailed, but we couldn’t stop. The moment I heard the motors roaring again, I knew that the Dieselheads were on our trail. And they’d stop at nothing to turn us into food… or something far more sinister.</p>
       <p>Rowan’s screams were leading them to us. I had to use the terrain to our advantage. I slipped us through wired fences, had us crawl beneath rusted machines, and when I saw the drainage tunnel, I threw Rowan ahead of me in hopes that if they spotted us, she’d have a running start.</p>
       <p>Her throat must have become inflamed by the amount she wailed. It pained me. I knew how much the bottle and its contents meant to her. If there was any luck, the Dieselheads would have left it behind after they called off the search. But truthfully, I never wanted to return to that beach again.</p>
       <p>The city was no longer safe for us. Now that the largest gang in the city knew that two young girls were running free, there’d be a wild hunt. Material goods meant little to aid our situation regardless of who that letter was from. But I knew better than to expect Rowan to think the same.</p>
       <p>As she held onto my hand, she dug her nails into my flesh. I saw the anger in her scowled expression. She wished to tear me to shreds quicker than the Dieselheads themselves. But that was something I could take. At the very least, she was safe.</p>

       <hr />

       <p>“I hate you!” Rowan cried.</p>
       <p>Tying the last rope around our makeshift sacks, we were finally packed and ready to leave for the countryside. I knew if we followed the drainage tunnels we’d be able to make our way to the river unseen. But beyond that, it was going to be sheer luck that there wasn’t a patrol. </p>
       <p>“Are you even listening!?” She was relentless, “We have to go back! We have to go now!”</p>
       <p>We had crawled through mud, sand, and sewers ever since we first came back to the surface. But I knew there had to be a better life out there for me and my sister. I just needed to find it. I took one of the sacks and tossed it to her. No more stalling. We had to get going.</p>
       <p>She let the bag slam into her chest and fall onto the ground, “You can’t just ignore me. You saw it. I know you did. The letter was in that bottle. And now those Dieselheads have it to… what if they just burn it or-”</p>
       <p>I put my hand on her shoulder, “Rowan. Think about this. Why would they even want some message in a bottle? It’s probably still sitting out there on the beach. It’s not gone to the world. But if we’re not gone out of here by tonight then-”</p>
       <p>“I’m going back for it first!” she screamed as she slapped my hand away.</p>
       <p>As she sprung for the doorway, I blocked her path. It was only sheer luck that allowed us to remain unscathed for as long as we had. I knew that if we spent one more night in the city, we would only be inviting a bitter end. I held my ground expecting her to lunge at me, but instead of anger, she showed only sorrow.</p>
       <p>Tears welled in her eyes as she spoke, “Does it actually mean that little to you? Those were the last words they left us. You don’t even want to know what they tried to tell us? Maybe they’re still alive and-”</p>
       <p>I knew where she was going with that thought, and I needed to stop her, “Ro. We have to keep moving. We knew we’d never see them again when we went into the shelter without them. That bottle was an empty promise. Do you know how many messages were probably thrown into the ocean? Before the bombs fell, do you really think they had a chance to sit down, write some letter, and toss it into the waves!?” </p>
       <p>“You’re heartless!” she screamed.</p>
       <p>My patience had worn thin, “I’m the only one of us who’s realistic. While you’re chasing some pipedream, I’m trying to keep us from getting killed! Do you <i>want</i> to die!? Tell me now. We can hold hands and scream and shout around the mountains until the Dieselheads find us.”</p>
       <p>“It’d be a lot better than being stuck with you forever! You know what I think? You’re a coward! You deny any hope so you can run away. Well, I’m sick of running! Gwen, our parents wouldn’t have lied to us. And I’m going to get that bottle and show you!”</p>
       <p>Before she could take another step, I grabbed her arm, “A coward, huh? I’m putting my neck on the line for both of us and <i>I’m</i> a coward? Let me tell you how it really is. You’re a spoiled brat who thinks she can have everything her way. Mom and dad aren’t around to give you whatever you want anymore! They only told you about the bottle so you’d shut up and get in the shelter!”</p>
       <p>Seeing her lip tremble, I knew I had gone too far. All of my frustrations culminated in those words. And after I said them, I only felt regret. As Rowan sobbed, I reached out to her. We fought, but at the end of the day, we were still sisters. I wanted her to know that I was only frustrated because I wanted to keep her safe.</p>
       <p>Rowan shoved my arms away. She ground her teeth together as she snarled, “I wish you had to stay behind instead!”</p>
       <p>Her words stung. As she ran down the halls and back into the sewer, I hadn’t the will left to chase her. There was a part of me that truly agreed with her. Our parents would have known what to do better than I would have. They would’ve kept Rowan safe and gave her all of the things she wanted. When it was me looking after her, I was just fumbling around trying to do anything right.</p>
       <p>I dropped to my knees. I felt too hollow to cry. Ever since the bombs fell, I hadn’t felt much of anything. I had kept everything I felt bottled away. There were plenty of times I wanted to give up. If I hadn’t had Rowan to protect, I probably would have plunged into the ocean and let the flowing waters take my body away.</p>
       <p>Rising to my feet, I knew I couldn’t sit and feel sorry for myself forever. Rowan was off getting herself in trouble yet again. Even if it would be the death of me, I was going to do everything in my power to keep her safe. I ran down the halls and found the open grate. If she was going to look for that stupid bottle, I wanted to be right there beside her.</p>

       <hr />

       <p>Combing the beach under moonlight, I had run until my throat became raw. Overexerting myself would only leave me winded. And after a day filled with panic, my heart and muscles couldn’t take much more. Instead of pausing to take a breath, however, I kept going. </p>
       <p>Rowan was nowhere to be found on the beach. The bottle wasn’t there either. The best-case scenario was that Rowan had found it and ran, but I didn’t believe in putting my faith in chance. Until she was in my sights, I had to prepare for the off-chance that she had gotten caught up with the Dieselheads.</p>
       <p>My eyes darted up to the mountains. A billowing flame wafted from the highest cliff. I may not have been up-to-date on all of the Dieselhead’s events and festivities, but I at least knew it wasn’t every night that they held a bonfire. Something got them riled up, and I needed to know what.</p>
       <p>Pushing myself further up the cliff trail, my heart was beating out of my chest. <i>“What was she thinking?”</i> Of all of the stupid ideas she could have had in her mind, she just had to rummage through the beach by herself. The gangs were probably waiting for us to be stupid enough to return, and she fell right into their trap.</p>
       <p>As I ascended higher, I caught a glimpse of those who had been less fortunate than myself. Piles of shattered bones and charred corpses littered the main passage to the highest cliff. I gagged as the scent of rotting flesh filled my nostrils. Seeing the burn wounds frightened me. I had to get to the top as soon as possible. But taking the main road would be a death sentence.</p>
       <p>Rocks tumbled from the cliffside walls as I scaled the ledge. Between tumbling down a mountain or being burned alive, I didn’t know which was worse. Well, I at least knew the worst fate was not making it to my sister in time. So despite inhaling particles of dirt, I kept my coughing contained as to not alert any listening ears.</p>
       <p>A crown of stones collected in my thick black hair. I had already failed at keeping it unmatted. Whatever twigs or leaves may have fallen into it, that way only a small price to pay for taking the unpaved trail. It was only a short climb before my feet were once again on solid earth. I didn’t even want to look down and see how high up I had traveled.</p>
       <p>But hearing flickering flames and voices chattering, I knew I was close. Just around the bend of the bushy trail, I saw a burning light. The Dieselhead camp was in my sights. Though, I still had to remain out of <i>their</i> sights. Spotting another shallow ledge higher up, I decided to attempt to get a view from above.</p>
       <p>Spotting the cages, my first thought was that Rowan had gotten herself kidnapped. Twisted metal from wire fences and welded street signs made the pens where huddled humans sat. Their eyes were sullen, but they were eyes unfamiliar to me. Rowan wasn’t among them.</p>
       <p>My eyes darted to the bonfire, fearing the scent of burning meat was from human flesh. But while the flames raged on and the grills smoked, there was no way I was going to be able to tell if those slabs of red meat were a stray dog or my sister. I just had to hope that the Dieselheads weren’t skilled enough to skin a human in less than an hour.</p>
       <p>Hearing footsteps barreling up the main path, I ducked down and hid in the bushes. I hoped Rowan wasn’t stupid enough to run into the camp face-first. But she had a knack for surprising me in the worst ways possible. Peeking up and seeing the mud-caked boy from the beach, however, I could sigh with some relief. </p>
       <p>“Nolan!” a gruff voice screamed, “You’re empty-handed! What happened!?”</p>
       <p>The boy, Nolan, took a moment to pant before standing upright and answering, “I searched that whole beach. They’re gone. Even if they’re still in the city, they’re probably gearing up to reach the outskirts anyway. Can’t we just call off the search until the morning?”</p>
       <p>Where a simple ‘no’ probably would have sufficed, the gruff-voiced man struck the boy, knocking him to his feet. With the world in shambles, I guess I didn’t expect ‘kindness’ to be the default. But even among their own, the Dieselheads only seemed to rule with fear and violence.</p>
       <p>“We saw them go into the sewers! Didn’t you check!? If they’ve survived out here for this long it means they have a camp of some sort. And that means there’s others.”</p>
       <p>Nolan nodded his head with hesitation, “I- I went all through those sewers. I didn’t hear or see anyone. Like I said, they got away.”</p>
       <p>That made me raise an eyebrow. If someone had been searching through the sewers after us, we would’ve heard something. Either Nolan was lying or he was far stealthier than he let on. Our ‘base of operations’ was easy to miss for the untrained eye. But if he had been not far behind us, his odds of finding us weren’t too bad.</p>
       <p>The gruff man must have thought the same because he grabbed the boy by his neck and lifted him into the air. Struggling and gasping for breath, Nolan ripped at his captor’s hands to break free as the man whipped him towards the flame. Even if he was a complete stranger, it still left me anxious watching what I assumed would be his demise.</p>
       <p>“I like to think I run a simple-enough-to-understand set of rules. You do what you’re told, you benefit the gang, and you get to reap the rewards,” the man said, “But if you’re incapable of doing your share… then why should I let you roam free?”</p>
       <p>While Nolan swung his body, desperately trying to break free, the sack slung around his shoulder fell. Under most circumstances, I wouldn’t have been interested to watch old books and cardboard scraps tumble down a mountainside. But it was the sound of rolling glass that caught my attention— he had the bottle with the message.</p>
       <p>Upon dropping it, the boy reached out for it. From where he dangled in the air, there was no way he could do much of anything. But still, he swung like a pendulum as he tried to catch the bottle before it rolled down the trail. I didn’t know what got him so interested in it. Though, I knew if I had that bottle in my possession, I wouldn’t have to worry about Rowan going off looking for it.</p>
       <p>I climbed down the shallow ledge and into the bushes. While the two fought, I had time to watch the bottle roll out of their sights. And that was my chance to grab it. Feeling the cold glass in my hands was like a weight lifted off of my shoulders. No more combing through the beaches. My sister and I could finally get out of the city.</p>
       <p>Even with one matter solved, there was still an even bigger dilemma. <i>Where</i> was Rowan? From what I heard the Dieselheads say, they still hadn’t found her. And because the bottle was now in my possession, I knew she hadn’t found that. I had searched every inch of that beach and still, she was nowhere. My heart pounded as I realized that I had no clue where to find my sister.</p>
       <p>Footsteps darted down the trail. I kept my body low and covered my mouth. Nolan was rummaging through the rocks and bones. He massaged his reddened neck as he searched for what I could only assume was the bottle. I didn’t know what it meant to him, but I could tell it meant a lot. Tears were welling up in his eyes.</p>
       <p>“Quit lazing about on the ground! Come tend to the meat!” the gruff voice screamed. </p>
       <p>Nolan scrambled to the cliff’s edge. I had to worry he was going to jump off in search of that bottle. But he sighed before holding his head and returning to the camp. I was able to get a closer look at him before he left. Beneath all of those layers of mud and sand, there was a kid not much older than my sister. It pained me knowing that even children were getting caught up doing the Dieselhead’s dirty work.</p>
       <p>Waiting for the camp to be distracted, I made my descent back to the beach. I had to search one last time. There was a chance she was roaming around the city as well, but I didn’t want to think that could be the case. One didn’t want to think about what lurked in those streets at night. My greatest hope was that she ran back into the sewers and was fast asleep.</p>

       <hr />

       <p>Cries echoed through the sewer tunnels as I made my way back. After searching the beach for what must have been an hour, I was relieved to finally hear my sister’s voice again. I wanted to shout out to her, but I knew the danger I’d put us in if I were too loud.</p>
       <p>She was balled up outside the grate of our makeshift home when I found her. Barely lifting her head, I saw her cheeks were puffy and her skin reddened. In the time that I had been sneaking around enemy territory, it looked like she had been left crying. Luckily, I had the very thing to put a smile on her face.</p>
       <p>“Ro, what are you doing!? I was worried sick! You don’t even want to know what I had to go through to find you. Where have you been all this time?” </p>
       <p>She groaned and rested her head against the concrete wall, “I wanted to go back to the beach… but I got scared. So I hid in one of the tunnels and… and… Gwen, we’ll never find it again, will we? Why can’t we just look one last time?”</p>
       <p>Before she could say another word, I pulled a ‘gift’ from inside my shirt and handed it to her. I don’t think Rowan comprehended exactly what was in front of her when I first held it forward. Her expression turned from shock— bulging eyes and mouth agape— to complete joy.</p>
       <p>Rowan lunged at me to hug me, nearly knocking the bottle out of my hands. It made me feel good that I could still be supportive of her as a big sister. But now was time for her to do something for me. And since I had done her the biggest favor I expected her to ask for, I figured she’d finally be okay with moving.</p>
       <p>“Listen. Rowan. I’m going to give this to you now, but you have to promise me something. We need to leave the city <i>now.</i> The Dieselheads know we’re out here, and they’re not going to give up until they find us. Once we get somewhere safe, you can read the message. But until then? We have to run.”</p>
       <p>Nodding, she was finally in agreement. But that was only the beginning of our journey. I couldn’t confirm how many scouts were sitting around in the outskirts, but I knew that if we didn’t leave soon, we’d only be making things harder for ourselves. Nolan unintentionally bought us time, and I couldn’t waste that good fortune.</p>
       <p>Grabbing our makeshift sacks, we were ready to set out for one of the long paths that opened up near the forest. I instructed Rowan to move quickly but silently, and I did the same. The sewer’s echoes made our journey more difficult. But after everything we had been through, I wasn’t about to give up.
        </p>
        <p>“Shh!” I called as I held out my hand to halt Rowan.</p>
        <p>Four adults stood by the entrance to the sewer. Their backs were facing the tunnel so I could confirm they hadn’t heard us. But with that many of them just outside, we were unable to move any further. I needed to think of a plan, and I needed it fast. </p>
        <p>Tossing any object at them was going to give out our location. And any shout or sound wouldn’t have much luck of frightening them. The best I could do was lay low and listen. There was no way that they could stay out there the entire night. Though, as I squinted and looked through the grate, I spotted sleeping bags. We were trapped.</p>
        <p>We couldn’t wait forever. And I knew that if we didn’t leave soon, the opportunity wouldn’t always be available to us. Peering down the tunnel, I knew there were twisting paths where one could easily get lost. I just had to hope that the Dieselheads didn’t know the layout better than I did.</p>
        <p>I turned to Rowan and whispered, “I’m going to bait them through the sewers until they get lost. What I need you to do is slip out of here and make for the forest as soon as the entrance is clear. Got it?”</p>
        <p>She tried to argue, but I hushed her. We didn’t have time to fight. Even she understood. “I need you to stay hidden in the forest. Once we’re together again, we’ll read the letter together. I promise.” </p>
        <p>As soon as I saw her nestled beneath heaps of discarded plywood, I rushed forward and shouted, “Hey! Looking for something!?”</p>
        <p>Without waiting for a reply, I turned and ran, their footsteps were all I needed to hear to know that my plan was already in motion. I waited for a moment outside the left side of the fork to make sure they saw which way I headed. And once they locked eyes on me, I barreled forward like my life depended on it. Truly, it did.</p>
        <p>The path I had taken looped around back to the right side of the fork. Though, there were a lot of detours in-between. As long as I could get the Dieselheads trapped in a maze, I’d have no worries that they’d be back near the forest to find us in a timely manner. Judging by how each of them moaned about the smell and lack of light, I knew I had them in the bag.</p>
        <p>I turned behind a wall just out of sight and dove behind a grate that was obscured by a tall cardboard sign. Nooks like those were useful hiding spots. And they were lifesavers when one needed to lose a pursuer. Hearing their footsteps approaching, I knew this was the make-or-break moment. If they found me, it would all be over.</p>
        <p>Their steps grew louder as did their strained breathing. And then in seconds, they became quiet again. Hearing their faint echoes ask, “Where did she go?” was the last confirmation I needed that they lost my trail. But until I met up with Rowan, I knew there was no time for celebration.</p>
        <p>I slipped out from the nook and tiptoed back towards the fork before sprinting full-speed ahead. There were many parts of the forest where Rowan could have hidden. But knowing her, there was one spot in particular. Back before everything went wrong, our parents took us out to the duck pond every weekend. It only seemed fitting that we’d read their message in that place.</p>

        <hr />

        <p>“Gwen!” she screamed as she saw me.</p>
        <p>I hushed her before reaching out to hug her. We weren’t yet in the clear, but we had made it far enough out of the city that we could rest a little easier. From the forest, there were a couple of checkpoints that still made me feel anxious. But I figured we had a brief moment to celebrate how far we had come.</p>
        <p>Rowan already had the bottle in her hands. I nodded to her, and she jammed her fingers inside, overzealous to have her prize. She wasn’t alone in wanting to read the message. As much as I was against putting our lives on the line to find it, I still wanted to hear our parent’s last words.</p>
        <p>Thinking back to the day we first went into that shelter, I could tell they had a lot on their minds that had been left unsaid. If they could have sat down and explained everything to us, I knew they would have. But we didn’t have time. The entire world didn’t have time.</p>
        <p>Tearing apart the plastic, Rowan hugged onto the letter like it was a lost puppy. She was holding what was probably the last fragments of mom and dad. Even I was tempted to reach out and touch it. But I wanted to let her savor the moment. And I knew she wanted to be the first to set her eyes on their handwriting and read it.</p>
        <p>She began, “I’m sorry I wasn’t able to be there with you. By the time you read this, I won’t be there to read you bedtime stories until the sun rises. And I won’t be there to watch over you and keep you safe. I know all of this is going to be hard on you, but you’re strong.”</p>
        <p>Her voice cracked as she continued, “Each day is going to bring new challenges. And I know at times you’re going to want to give up. But you need to keep fighting. Me staying behind is not me abandoning you. This is my way of ensuring a future where you can live a long and healthy life.”</p>
        <p>“I wish I could write a thousand words to you. But you’ll have to forgive me for my brevity,” Rowan scrunched her face as she paused, “Just knowing that my son is safe is enough to ease my mind. I love you, Nolan. From Mom.”</p>
        <p>My heart sank as Rowan looked at me, “”G-Gwen? What is this? Who’s Nolan?” </p>
        <p>Her breathing quickened and she began to scream. I knew I needed to tell her to keep quiet, but my own mind was blank. I felt like an idiot. I never once stopped to consider the thought that someone else would be out there searching for a message in a bottle. And by the time I came to my senses, I knew I needed to do something stupid.</p>
        <p>“Ro,” I said calmly, “We need to go back.”</p>
        </div>
      </section>
    </div>
    </div>
  </Layout>
);

export default IndexPage;
